### ISSUE TITLE
sample calculator server compile error with vs2015 update3

### ISSUE THREAD

**Issue by nneesshh** [sandstorm-io/capnproto#413] opened 2017-02-11 16:36 UTC
1>..\src\Capnproto\calculator-server.c++(84): error C2558: class 'Calculator::Function::Client': no copy constructor available or copy constructor is declared 'explicit'
1>..\src\Capnproto\calculator-server.c++(125): error C2558: class 'capnp::CallContext<Calculator::Function::Server::CallParams,Calculator::Function::Server::CallResults>': no copy constructor available or copy constructor is declared 'explicit'
1>..\src\Capnproto\calculator-server.c++(173): error C2558: class 'capnp::CallContext<Calculator::Server::EvaluateParams,Calculator::Server::EvaluateResults>': no copy constructor available or copy constructor is declared 'explicit'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by harrishancock** [comment] 2017-02-11 23:30
The build error here is caused by an MSVC compiler bug: when capturing variables by value in lambda capture lists, MSVC only appears to consider const copy constructors (`Foo::Foo(const Foo&)`) and never mutable copy constructors (`Foo::Foo(Foo&)`). You can see my initial discovery of the problem at f87b306, and some discussion with @kentonv in #396.

There's an easy workaround: wrap variables with mutable copy constructors in `KJ_CPCAP(...)` when capturing them, which forces MSVC to perform a copy manually. I'll have a patch ready soon that does that for this particular instance of the problem.

However, you will probably run into this bug in the future until we can fully resolve the root cause, either by a fix from Microsoft or by removing the use of mutable copy construction in the codebase.

**Comment by kentonv** [comment] 2017-04-23 17:57
Looks like this was fixed by #414.

**Closed by kentonv** 2017-04-23 17:57 UTC
