### ISSUE TITLE
Receiving a too-large message ruins that connection for future messages

### ISSUE THREAD

**Issue by asilversempirical** [sandstorm-io/capnproto#407] opened 2017-01-24 21:57 UTC
If you receive a message longer than your client's traversalLimitInWords it seems to no longer be able to receive any more messages without tripping the client-side check at https://github.com/sandstorm-io/capnproto/blob/master/c%2B%2B/src/capnp/serialize-async.c%2B%2B#L119.

I have a demonstration with a failing test which I believe should pass at https://github.com/sandstorm-io/capnproto/pull/406.

I tried to figure out what's going on, but I'm a bit stuck without knowing more of the internals. The first small response has a single segment, but the second small response (after the failed large one) has two segments, where the first is exceedingly large. But I'm struggling to figure out whether it's mis-reading that value and actually the response _is_ small, or if the server is getting confused and sending an abnormally large response.

**Comment by kentonv** [comment] 2017-01-25 00:50
Hi @asilversempirical,

Thank you for the awesome test case!

It's considered a protocol error for a client to send a too-large message. The receiver is actually supposed to send an `Abort` message back to the sender and then close the connection. But it sounds like you're seeing the receiver try to read further messages -- perhaps after having not fully read the previous message, therefore it's reading from the wrong point in the stream, which could lead to all sorts of confusion. That seems like a bug, but fixing it won't solve your higher-level problem.

There really isn't any way we could make the receiver recover after a too-large message. Since it can't actually process that message, its state would become de-synchronized from the sender's state. In most cases this would result in a call that never returns, which is no good.

As I think you noticed while writing your test, I recently added a check to the sending side that avoids sending a message which is over the sender's traversal limit (see 6cf522b26ef9a397e6ae49b1fb46f6af2dd56e53). But as your test demonstrates, there is still a problem if the sender and receiver don't agree on limits. FWIW I would recommend documenting a standard limit for your protocol to avoid this. (In general I'd recommend sticking to the default limit unless there's a really good reason not to.)

**Comment by asilversempirical** [comment] 2017-01-25 01:01
Ahh, got it. Yes, reading from an undefined point in the stream would explain where it's getting the confused first word from.

And yes, I was surprised that the client didn't automatically close the connection, which was the main reason I thought recovery might be an option. So it sounds like not closing might be a bug?

We do try to pick a standard limit, but we're currently stuck until https://github.com/jparyani/pycapnp/pull/126 lands since our python client has no way of increasing its limit. Our really good reason is that we're slinging some large protos around :).

Thanks for the quick response! That was super helpful. I'll close out that PR (I actually intended it to be on my fork anyway. Oops.) Would you like me to keep this issue open to document the question about closing the client, or close this out as well?

**Comment by kentonv** [comment] 2017-01-25 01:20
Yes, let's keep the issue open, although it seems non-urgent.

For bulk transfers, I recommend splitting the data up into chunks transferred over multiple calls. You might take a look at Sandstorm's `ByteStream` interface (it's simple, but illustrative):

https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/util.capnp#L69

Using multiple calls not only avoids the limit (which exists for security reasons) but also allows other communications to be interleaved with the transfer. In the future I hope to take this further by adding a way to mark certain calls (`write()`, in this case) as bulk-transfer calls, which would allow the RPC system to prioritize non-bulk calls over them.

**Comment by kentonv** [comment] 2017-04-26 00:32
On reviewing your test case (again, thank you so much for providing a whole working test!), it looks like the behavior is as intended: the connection is disconnected, and all subsequent calls over it throw the same exception reporting why the disconnect occurred. So, I don't think there's actually a bug here, but let me know if you disagree.

**Closed by kentonv** 2017-04-26 00:32 UTC
