### ISSUE TITLE
cygwin, failure in capnp-test.log during "make check"

### ISSUE THREAD

**Issue by echoma** [sandstorm-io/capnproto#234] opened 2015-08-19 15:07 UTC
```
[----------] 7 tests from AsyncIo
[ RUN      ] AsyncIo.SimpleNetwork
unknown file: Failure
C++ exception with description "src/kj/async-io.c++:350: failed: ::socket(addr.generic.sa_family, type, 0): Address family not supported by protocol" thrown in the test body.
[  FAILED  ] AsyncIo.SimpleNetwork (10 ms)
[ RUN      ] AsyncIo.AddressParsing
[       OK ] AsyncIo.AddressParsing (2384 ms)
[ RUN      ] AsyncIo.OneWayPipe
[       OK ] AsyncIo.OneWayPipe (0 ms)
[ RUN      ] AsyncIo.TwoWayPipe
[       OK ] AsyncIo.TwoWayPipe (0 ms)
[ RUN      ] AsyncIo.PipeThread
[       OK ] AsyncIo.PipeThread (0 ms)
[ RUN      ] AsyncIo.PipeThreadDisconnects
[       OK ] AsyncIo.PipeThreadDisconnects (0 ms)
[ RUN      ] AsyncIo.Timeouts
[       OK ] AsyncIo.Timeouts (10 ms)
[----------] 7 tests from AsyncIo (2404 ms total)


[----------] Global test environment tear-down
[==========] 405 tests from 45 test cases ran. (7581 ms total)
[  PASSED  ] 404 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AsyncIo.SimpleNetwork

 1 FAILED TEST
```
How can I fix this?

**Comment by kentonv** [comment] 2015-08-19 18:29
Hmm, I'm not immediately sure what might have caused this. Unfortunately we don't get stack traces on Cygwin, which makes things a lot harder to debug.

Since this is the first time someone has reported this, likely there's something unusual about your system. Most likely the test failure is a problem with the test, but not a problem you actually need to worry about when using Cap'n Proto. That said, we should fix the test if we can.

Questions:
- Is your system configured for ipv4, ipv6, or both?
- Does `localhost` properly resolve to `127.0.0.1` and/or `::1` on your machine? Which one does it resolve to first?
- If you change the test to replace both the strings `"localhost"` and `"*"` with `"127.0.0.1"`, does it work better?

**Comment by echoma** [comment] 2015-08-21 16:03
sorry for late reply.
* the system is ipv4 only
* localhost is properly resolved to 127.0.0.1
* how can I do this? which file should I edit?

**Comment by kentonv** [comment] 2015-08-21 18:27
Sorry, the file is `src/kj/async-io-test.c++`. The very first test in that file is failing. There's two calls to `parseAddress` in the test body, one taking `"localhost"` as a parameter and the other taking `"*"`. Try replacing both strings with `"127.0.0.1"`.

**Comment by echoma** [comment] 2015-08-21 23:12
all test success with "127.0.0.1", great!

**Comment by kentonv** [comment] 2015-08-21 23:29
Still, this doesn't quite explain what's wrong. My guess is that `localhost` mapped (incorrectly) to both ipv4 and ipv6 versions of the address, but your machine only actually supports ipv4. I don't really have the bandwidth to debug this, though...

**Comment by echoma** [comment] 2015-09-18 10:52
So..how can I help?

**Comment by kentonv** [comment] 2015-09-18 22:06
Well, if you want to help, you can try to debug the problem. I guess that means figuring out what address family is being passed to `socket()` and why `localhost` mapped to that type when it isn't supported, then figuring out how to detect this situation and avoid it. Then send me a pull request with the fix. :)

But again, Cap'n Proto almost certainly will work fine for you despite this problem, so if you'd rather just ignore it that's probably fine too.

**Comment by echoma** [comment] 2015-09-21 01:14
This problem didn't show again with "localhost" as parameter. Maybe this is a bug of cygwin, cygwin has upgraded several times since I open this issue.

**Comment by kentonv** [comment] 2015-09-25 22:00
OK, let's close this then. Let me know if it re-appears.

**Closed by kentonv** 2015-09-25 22:00 UTC

**Comment by olsonanl** [comment] 2017-01-03 22:16
I just came across this error on a CentOS 6.8 system; changing * to 127.0.0.1 fixed the problem.

Hosts file contains

127.0.0.1	localhost.localdomain localhost 
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

I don't see an active ipv6 address assignment on the live interfaces.

**Comment by kentonv** [comment] 2017-01-03 23:51
Hmm, I tried on centos 7.2 on Digital Ocean and wasn't able to reproduce. :/
