### ISSUE TITLE
*.capnp files not installed on Windows

### ISSUE THREAD

**Issue by df2218380513f49d8a3d896fc45740e9** [sandstorm-io/capnproto#398] opened 2016-12-25 23:38 UTC
this should be easy to fix but I don't know any cmake :disappointed:

**Comment by kentonv** [comment] 2017-01-04 00:42
It looks like they should be installed along-side the headers. See e.g.:

https://github.com/sandstorm-io/capnproto/blob/master/c++/src/capnp/CMakeLists.txt#L67
https://github.com/sandstorm-io/capnproto/blob/master/c++/src/capnp/CMakeLists.txt#L100
https://github.com/sandstorm-io/capnproto/blob/master/c++/src/capnp/CMakeLists.txt#L121

What are you observing in practice?

**Comment by df2218380513f49d8a3d896fc45740e9** [comment] 2017-01-04 04:12
I see the headers installed, but not the schemas. The only other thing of note is that I'm using CMAKE_INSTALL_PREFIX to install into a custom location, but given the code you've just pointed me to and the fact that the headers make it, please close this issue if you can't reproduce it!

**Comment by kentonv** [comment] 2017-01-05 00:49
I haven't actually tried it myself -- I'm not very familiar with cmake.

@pqu @joshuawarner32 any ideas?

**Comment by pqu** [comment] 2017-01-05 04:18
I unfortunately don't have a Windows machine handy anymore, but the schema files make it into place on a Mac OS X build and I can't see anything obvious that would make a Windows build behave differently.

**Comment by harrishancock** [comment] 2017-01-05 19:17
Will test this tonight.

**Comment by harrishancock** [comment] 2017-01-06 18:42
Tried with a custom CMAKE_INSTALL_PREFIX. I cannot reproduce the problem -- for every .capnp.h I see a corresponding .capnp file sitting right next to it.

@df2218380513f49d8a3d896fc45740e9 If you can still reproduce the issue, can you give us the exact sequence of steps that you're taking?

**Comment by kentonv** [comment] 2017-04-23 18:05
Closing since we can't reproduce.

**Closed by kentonv** 2017-04-23 18:05 UTC
