### ISSUE TITLE
linker segfaults when building capnproto with -flto and -O2

### ISSUE THREAD

**Issue by vitaly-krugl** [sandstorm-io/capnproto#300] opened 2016-03-30 07:04 UTC
I am seeing this linker segfault when building capnproto on Travis as well as on Ubuntu:

```
Linking CXX executable capnp
stringify.c++.o (symbol from plugin): warning: memset used with constant zero length parameter; this could be due to transposed parameters
/home/guest/CapnSegfault/build/scripts/CapnProto-prefix/src/CapnProto/src/kj/parse/common.h: In member function ‘operator()’:
/home/guest/CapnSegfault/build/scripts/CapnProto-prefix/src/CapnProto/src/kj/parse/common.h:639:7: internal compiler error: Segmentation fault
       operator()(Input& input) const {
```

The toolchain is:
```
$ uname -a
Linux guest-VirtualBox 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

$ cmake --version
cmake version 2.8.12.2
```

To reproduce, create the following directory tree:
```
CapnProtoBuild/
  CMakeLists.txt
  build/
    scripts/
```

And place the cmake script below into CMakeLists.txt
```
cmake_minimum_required(VERSION 2.8)
project(nupic_core CXX)

include(ExternalProject)

set(cxx_flags "-fPIC -flto -O2")

set(linker_flags "-flto -O2")

ExternalProject_Add(CapnProto
  URL https://capnproto.org/capnproto-c++-0.5.3.tar.gz

  UPDATE_COMMAND ""

  CMAKE_GENERATOR ${CMAKE_GENERATOR}

  STEP_TARGETS install

  CMAKE_ARGS
      -DCMAKE_BUILD_TYPE=Release
      -DCAPNP_LITE=0
      -DBUILD_SHARED_LIBS=OFF
      -DBUILD_TESTING=OFF
      -DCMAKE_CXX_FLAGS=${cxx_flags}
      -DCMAKE_EXE_LINKER_FLAGS=${linker_flags}
      -DCMAKE_MODULE_LINKER_FLAGS=${linker_flags}
      -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/ThirdParty/Install
)
```
Then
> cd CapnProtoBuild/build/scripts
> cmake ../.. -DCMAKE_INSTALL_PREFIX=../release -DCMAKE_BUILD_TYPE=Release
> make

**Comment by kentonv** [comment] 2016-04-01 19:59
I'm unable to reproduce this with G++ 4.9 nor 5.3, which are what I have readily available on my system. I used the cflags and ldflags you specified. Of course, any ICE is technically a compiler bug. Do you have any other compiler versions you can use?

**Comment by vitaly-krugl** [comment] 2016-04-12 23:42
@kentonv: thanks for checking. I am presently limited by the build system as to the toolchain version. I agree that this is most likely a compiler bug; I posted it here in case others have encountered it and are aware of a performant workaround with the stated toolchain version. Thx.

**Comment by kentonv** [comment] 2016-04-15 02:12
OK, I'm closing this since there's likely little we can do about it, though if you do discover a simple work-around that doesn't harm the Cap'n Proto code, feel free to send a pull request.

**Closed by kentonv** 2016-04-15 02:12 UTC
