### ISSUE TITLE
AsyncUnixTest::UrgentObserver spins forever on macOS 10.12

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/capnproto#374] opened 2016-10-02 18:24 UTC
cf https://github.com/sandstorm-io/capnproto/pull/239
cc @mologie

**Comment by dwrensha** [comment] 2016-10-02 18:29
Here are some test programs illustrating what's happening:

```c
// urgent_poll_server.c

#include "unistd.h"
#include "stdio.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>

int main() {
  int sock_fd = socket(AF_INET, SOCK_STREAM, 0);
  if (sock_fd < 0) {
    return -1;
  }

  struct sockaddr_in saddr = {};
  saddr.sin_family = AF_INET;
  saddr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
  saddr.sin_port = htons(10101);

  if (0 > bind(sock_fd, (struct sockaddr*)&saddr, sizeof(saddr))) {
    return -1;
  }

  socklen_t saddrLen = sizeof(saddr);
  if (0 > getsockname(sock_fd, (struct sockaddr*)(&saddr), &saddrLen)) {
    return -1;
  }

  if (0 > listen(sock_fd, 1)) {
    return -1;
  }

  while (1) {
    struct sockaddr_in caddr;
    socklen_t caddrLen = sizeof(caddr);
    int client_fd = accept(sock_fd, (struct sockaddr*)(&caddr), &caddrLen);

    if (client_fd < 0) {
      return -1;
    }

    char c;
    c = 'i';
    if (0 > send(client_fd, &c, 1, 0)) return -1;
    c = 'o';
    if (0 > send(client_fd, &c, 1, MSG_OOB)) return -1;

    int num_read = recv(client_fd, &c, 1, 0);
    if (num_read < 0 ) return -1;
    if (num_read == 0) {
      printf("expected 'q', got EOF\n");
      return -1;
    }
    if (c != 'q') {
      printf("expected 'q', got %c\n", c);
      return -1;
    }

    printf("success\n");
  }
}
```

```c
// urgent_poll_client.c

#include <fcntl.h>
#include "unistd.h"
#include "stdio.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <poll.h>

int main() {
  int sock_fd = socket(AF_INET, SOCK_STREAM, 0);
  if (sock_fd < 0) {
    return -1;
  }

  struct sockaddr_in saddr = {};
  saddr.sin_family = AF_INET;
  saddr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
  saddr.sin_port = htons(10101);
  if (0 > connect(sock_fd, (struct sockaddr*)&saddr, sizeof(saddr))) {
    return -1;
  }

  struct pollfd pfd;
  pfd.fd = sock_fd;
  pfd.events = POLLPRI;
  pfd.revents = 0;

  int poll_result = poll(&pfd, 1, -1);
  // Timeout of -1 means that we should not get here unless poll hit an error
  // there is data on our file descriptor.

  if (poll_result < 0) {
    return -1;
  }

  // I expect `poll_result` to equal "1" and `pfd.revents` to equal `POLLPRI`.
  // Instead, both equal zero!
  if (poll_result == 0) {
    printf("poll() unexpectedly returned 0\n");
  }
  if (pfd.revents == 0) {
    printf("revents is unexpectedly equal to 0\n");
  }

  // If we pretend that `poll()` returned the results that we expected,
  // everything still works.

  char c;
  int n = recv(sock_fd, &c, 1, MSG_OOB);
  if (n < 1 || c != 'o') return -1;

  n = recv(sock_fd, &c, 1, 0);
  if (n < 1 || c != 'i') return -1;

  c = 'q';
  if (0 > send(sock_fd, &c, 1, 0)) return -1;
}
```

If I run `./urgent_data_server` in one terminal and then `./urgent_data_client` in another terminal, I expect the server to print "success" and the client to successfully exit, printing nothing. On Linux, that's exactly what happens. On macOS 10.12, the client prints:

```
$ ./urgent_poll_client 
poll() unexpectedly returned 0
revents is unexpectedly equal to 0
```

**Comment by mologie** [comment] 2016-10-02 18:57
Apple's implementation of OOB on TCP loopback sockets had its issues before. Namely, commenting out the first `send` call in your server example causes `poll` on the client to never return. I found that normal stream data must be available for the test to work on macOS, which is why this line was found in the test in the first place (I also mention this in a comment in the original test).

I can confirm that the test and your example break on macOS 10.12. I'd classify this as a regression in macOS, as clearly shown by your extended example, and suggest to simply disable the test on macOS until the issue is resolved by Apple. Disabling the test should do no harm because POLLPRI is an implementation-specific signal. The test was supposed to validate integration of POLLPRI with libkj in general.

If you know about an alternative interface on macOS which might emit POLLPRI, then I could update the test to make use of it. If you'd like to, I can also coordinate filing a Radar ticket with Apple. Right now, however, I have no use for POLLPRI on macOS at all, so this may be wasted time/effort and could be closed with a remark in the documentation warning the user about the broken OS interface.

**Comment by kentonv** [comment] 2016-10-12 02:56
Apparently poll() on macOS 10.12 is really, really broken: https://daniel.haxx.se/blog/2016/10/11/poll-on-mac-10-12-is-broken/

**Comment by dwrensha** [comment] 2017-01-27 04:02
On MacOS 10.12.3, the `AsyncUnixTest/UrgentObserver` test still spins forever for me. (It has, however, been ifdef'ed out of the capnp test suite by https://github.com/sandstorm-io/capnproto/commit/9591f2f36db505e67e8f9edfd01e35b66c998e3b.)

**Comment by kentonv** [comment] 2017-04-23 18:28
Closing since skipping the test seems like all we can do for now.

**Closed by kentonv** 2017-04-23 18:28 UTC

**Comment by kentonv** [comment] 2017-04-27 21:15
On Cygwin I observe that reading the OOB byte first seems to lead to a bug where the subsequent attempt to read the regular byte blocks until the connection closes. Bleh.
